name: yd_audio_players
description: A new flutter plugin project.
version: 0.0.1
authors: [yuzhipeng<wincoke@163.com>,wuximiao<wudijimao@qq.com>,guojinyu<guojinyu@corp.netease.com>,chedechao<chedechao333@163.com>]
homepage: https://github.com/YoudaoNetease/YDAudioPlayersForFlutterPlugin.git

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  uuid: ^2.0.0
  path_provider: ^1.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.11.3+17
  test: ^1.3.0

flutter:

  plugin:
    androidPackage: com.yd.yd_audio_players
    pluginClass: YDAudioPlayersPlugin
